### ISSUE TITLE
Declare a basic type field?

### ISSUE THREAD

**Issue by kehrazy** [kelpsyberry/proc-bitfield#2]
example:
```rust
bitfield! {
    #[repr(C)]
    pub struct Values(pub i32) {
        pub first: u8 @ 0..4,
        pub text: [c_char; 8],
    }
}
```
this fails with
> evaluation of constant value failed: attempt to compute `0_usize - 1_usize`, which would overflow

**Comment by kelpsyberry** [comment]
I'm really sorry for missing this issue! As for the example, I'm sorry, but it doesn't seem like valid syntax since the field bit range specification is missing from `text`... Still, such an assert only triggers when the bit range for a field spans beyond its bit size, beyond the bit size of the bitfield itself or is otherwise invalid. Could you send a more specific example?

**Comment by kehrazy** [comment]
> I'm really sorry for missing this issue! As for the example, I'm sorry, but it doesn't seem like valid syntax since the field bit range specification is missing from `text`... Still, such an assert only triggers when the bit range for a field spans beyond its bit size, beyond the bit size of the bitfield itself or is otherwise invalid. Could you send a more specific example?

Yeah, no worries! The problem is exactly that - the specification of the `text` field is a char array, not a _bitfield field_ - this syntax does not seem to be supported with this crate.

**Comment by kelpsyberry** [comment]
What about this solution? It would work syntax-wise, though using arrays as fields needs a custom `BitRange`  implementation for now.
```rust
bitfield! {
    #[repr(C)]
    pub struct Values(pub i32) {
        pub first: u8 @ 0..4,
        pub text: [c_char; 8] @ ..,
    }
}
```
